Update trim and sqlite3 with error checking

diff --git a/prebuilt/common/bin/boot_sqlite3 b/prebuilt/common/bin/boot_sqlite3
--- a/prebuilt/common/bin/boot_sqlite3
+++ b/prebuilt/common/bin/boot_sqlite3
@@ -2,59 +2,77 @@
 # Vacuum and reindex sqlite databases on boot
 
 LOGCAT="log -p i -t boot_sqlite3"
-LOG=/system/etc/logs/boot_sqlite3.log
+LOG=/data/local/logs/boot_sqlite3.log
+
+function log() {
+	$LOGCAT $1
+	echo $1 | tee -a $LOG
+}
 
 function sqlite3() {
-	# Mount system
-    	$LOGCAT "Mounting /system";
-    	mount -o remount,rw /system;
-
 	# Check if log dir exists
 	if [ ! -d /system/etc/logs ]; then
 		$LOGCAT "Error: /system/etc/logs not found!";
+		mkdir -p /data/local/logs
+		SUCCESS=$?
+		if [[ $SUCCESS != 0 ]]; then
+			$LOGCAT "Error: Unable to create /data/local/logs!"
+		fi
 	fi
 	
     	# Create log file
-    	$LOGCAT "Creating new LOG file";
     	date > $LOG;
+    	$log "Creating new LOG file";
 	
 	# Check if logfile was created properly
 	if [ ! -e $LOG ]; then
     	    $LOGCAT "Error: Unable to create logfile!"
     	fi
 	
-	$LOGCAT "Beginning 1 minute delay..."
-	sleep 60;
-	$LOGCAT "Executing SQlite3!"
+	$log "Executing SQlite3!"
 	
-	echo "Beginning /data optimization" | tee -a $LOG
-	x=0;
+	$log "Beginning /data optimization"
+	COUNT=0;
 	for i in \
 	`find /data -iname "*.db"`;
 	do \
 		/system/xbin/sqlite3 $i 'VACUUM;' | tee -a $LOG;
+		SUCCESS=$?
+		if [[ $SUCCESS != 0 ]]; then
+			$log "Couldn't vaccuum $i";
+		fi
 		/system/xbin/sqlite3 $i 'REINDEX;' | tee -a $LOG;
-		x=$((x+1));
+		SUCCESS=$?
+		if [[ $SUCCESS != 0 ]]; then
+			$log "Couldn't re-index $i";
+		fi
+		$log "Optimized $i";
+		COUNT=$((COUNT+1));
 	done;
-	$LOGCAT "Optimized $x /data databases";
-	echo "Optimized $x /data databases" | tee -a $LOG
-	echo " " | tee -a $LOG
+	$log "Optimized $COUNT /data databases";
 	
-	echo "Beginning /sdcard optimization" | tee -a $LOG
-	x=0;
+	$log "Beginning /sdcard optimization";
+	COUNT=0;
 	for i in \
 	`find /sdcard -iname "*.db"`;
 	do \
 		/system/xbin/sqlite3 $i 'VACUUM;' | tee -a $LOG;
+		SUCCESS=$?
+                if [[ $SUCCESS != 0 ]]; then
+                        $log "Couldn't vaccuum $i";
+                fi
 		/system/xbin/sqlite3 $i 'REINDEX;' | tee -a $LOG;
-		x=$((x+1));
+		SUCCESS=$?
+                if [[ $SUCCESS != 0 ]]; then
+                        $log "Couldn't re-index $i";
+                fi
+		$log "Optimized $i";
+		COUNT=$((COUNT+1));
 	done;
-	$LOGCAT "Optimized $x /sdcard databases";
-	echo "Optimized $x /sdcard databases" | tee -a $LOG
+	$log "Optimized $COUNT /sdcard databases";
 
-	$LOGCAT "/system/etc/11sqlite3 complete!";
-	echo "SQlite3 optimization complete!" | tee -a $LOG
+	$log "SQlite3 optimization complete!";
 }
 
-$LOGCAT "Running /system/etc/11sqlite3...";
-sqlite3 &
+$log "Running boot_sqlite3...";
+su -c sqlite3 &
diff --git a/prebuilt/common/bin/boot_trim b/prebuilt/common/bin/boot_trim
--- a/prebuilt/common/bin/boot_trim
+++ b/prebuilt/common/bin/boot_trim
@@ -2,59 +2,78 @@
 # TRIM fat on every boot
 
 LOGCAT="log -p i -t boot_trim"
-LOG=/system/etc/logs/boot_trim.log
+LOG=/data/local/logs/boot_trim.log
+
+function log() {
+	$LOGCAT $1
+	echo $1 | tee -a $LOG
+}
 
 function trim() {
-    	# Mount system
-    	$LOGCAT "Mounting /system";
-    	mount -o remount,rw /system;
-	
 	# Check if log dir exists
 	if [ ! -d /system/etc/logs ]; then
 		$LOGCAT "Error: /system/etc/logs dir not found!";
+		mkdir -p /data/local/logs
+		SUCCESS=$?
+		if [[ $SUCCESS != 0 ]]; then
+			$LOGCAT "Error: Unable to create /data/local/logs"
+		fi
 	fi
 
     	# Create log file
-    	$LOGCAT "Creating new LOG file";
     	date > $LOG;
+    	$log "Creating new LOG file";
 
     	if [ ! -e $LOG ]; then
-        	$LOGCAT "Error: Unable to create logfile!"
+        	$log "Error: Unable to create logfile!"
     	fi
 
-	$LOGCAT "Beginning 1 minute delay..."
-    	sleep 60;
-	$LOGCAT "Executing TRIM!"
+	$log "Executing TRIM!"
 
     	# TRIM /system, if not F2FS
     	if ! mount | grep \/system | grep f2fs; then
-    	    	$LOGCAT "Trimming /system...";
+    	    	$log "Trimming /system...";
     		fstrim -v /system 2>&1 | tee -a $LOG;
+		SUCCESS=$?
+		if [[ $SUCCESS == 0 ]]; then
+			$log "Trimmed /system!"
+		else
+			$log "Error: Unable to trim /system!"
+		fi
     	else
-        	$LOGCAT "Unable to trim /system";
-        	echo "/system formatted as F2FS, TRIM not available!" | tee -a $LOG;
+        	$log "/system formatted as F2FS, TRIM not available!"
     	fi
 
     	# TRIM /data, if not F2FS
     	if ! mount | grep \/data | grep f2fs; then
-        	$LOGCAT "Trimming /data...";
+        	$log "Trimming /data...";
         	fstrim -v /data 2>&1 | tee -a $LOG;
+		SUCCESS=$?
+                if [[ $SUCCESS == 0 ]]; then
+                        $log "Trimmed /data!"
+                else
+                        $log "Error: Unable to trim /data!"
+                fi
     	else
-        	$LOGCAT "Unable to trim /data";
-        	echo "/data formatted as F2FS, TRIM not available!" | tee -a $LOG;
+        	$log "/data formatted as F2FS, TRIM not available!"
     	fi
 
     	# TRIM /cache, if not F2FS
    	if ! mount | grep \/cache | grep f2fs; then
-        	$LOGCAT "Trimming /cache...";
+        	$log "Trimming /cache...";
         	fstrim -v /cache 2>&1 | tee -a $LOG;
+		SUCCESS=$?
+                if [[ $SUCCESS == 0 ]]; then
+                        $log "Trimmed /cache!"
+                else
+                        $log "Error: Unable to trim /cache!"
+                fi
     	else
-        	$LOGCAT "Unable to trim /cache";
-        	echo "/cache formatted as F2FS, TRIM not available!" | tee -a $LOG;
+        	$log "/cache formatted as F2FS, TRIM not available!"
     	fi
 
-    	$LOGCAT "/system/etc/10fstrim complete!";
+    	$LOGCAT "boot_trim complete!";
 }
 
-$LOGCAT "Running /system/etc/10fstrim...";
-trim &
+$LOGCAT "Running boot_trim...";
+su -c trim &
